version: '3.8'

services:
  # Redis Service
  redis:
    image: redis:alpine
    container_name: bondhu-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bondhu-network

  # Main Application Service
  bondhu-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bondhu-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - bondhu-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker Service
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bondhu-celery-worker
    command: celery -A core.celery_app worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - bondhu-network

  # Celery Beat Service (for scheduled tasks)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bondhu-celery-beat
    command: celery -A core.celery_app beat --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - bondhu-network

  # Flower - Celery Monitoring (Optional)
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bondhu-flower
    command: celery -A core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - bondhu-network

volumes:
  redis-data:
    driver: local

networks:
  bondhu-network:
    driver: bridge