# Generated by Django 4.2.7 on 2025-07-31 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcementLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_vector', models.JSONField(default=list)),
                ('personality_vector', models.JSONField(default=list)),
                ('context_vector', models.JSONField(default=list)),
                ('policy_weights', models.JSONField(default=dict)),
                ('value_function', models.JSONField(default=dict)),
                ('exploration_rate', models.FloatField(default=0.1)),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('total_rewards', models.FloatField(default=0.0)),
                ('average_reward', models.FloatField(default=0.0)),
                ('last_action', models.JSONField(blank=True, default=dict)),
                ('last_reward', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rl_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('personality_classifier', 'Personality Classifier'), ('sentiment_analyzer', 'Sentiment Analyzer'), ('rl_agent', 'Reinforcement Learning Agent'), ('recommendation_engine', 'Recommendation Engine'), ('mood_detector', 'Mood Detector'), ('response_generator', 'Response Generator')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('file_path', models.CharField(max_length=500)),
                ('config', models.JSONField(default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_data_size', models.PositiveIntegerField(blank=True, null=True)),
                ('training_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('failed', 'Failed')], default='training', max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
    ]
